FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /app

COPY . ./

RUN dotnet restore "API/ProjecteEmbassaments/ProjecteEmbassaments.csproj"

RUN dotnet publish "API/ProjecteEmbassaments/ProjecteEmbassaments.csproj" -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
COPY --from=build /app/out .

COPY mesura.csv .

EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

ENTRYPOINT ["dotnet", "ProjecteEmbassaments.dll"]